version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: scholanova_project_store

jobs:
  test_java:
    executor: java-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - test_java
